# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
swift_version = "3.2"

target 'LogInSystem' do
  use_frameworks!
  pod ‘Alamofire’#, '~> 4.6.0'
  pod ‘SwiftyJSON’#, ‘~> 4.0.0’
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if ['Alamofire'].include? target.name
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '3.2'
              end
          end
      end
  end
end
#post_install do |installer| installer.pods_project.build_configurations.each do |config| config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = '' end
