# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LogInSystem' do
  use_frameworks!
  pod ‘Alamofire’, '~> 4.6.0'
  pod ‘SwiftyJSON’, ‘~> 4.0.0’
end
